Задача "Двоичное представление"
YuriUfimtsev/Space-for-homeworks pull request #11
Opened 2021-10-09 10:20 UTC by YuriUfimtsev

2021-10-09 15:10 UTC, yurii-litvinov requested changes

2021-10-09 15:10 UTC, yurii-litvinov commented on Homework 4/Binary representation/Binary representation/Binary representation.c
> +}
Не-а, это всё не нужно. Числа в памяти хранятся и так в дополнительном коде, надо просто прочитать их битовое представление (как раз с помощью битовых масок, про которые речь шла на паре --- арифметические операции тоже могут подойти, но, во-первых, сбивают, заставляя думать про число как про число, а не последовательность бит, а во-вторых, там могут быть заморочки со знаками). В правильном решении вообще не надо проверять знак числа, и даже число ли это: мы пробегаемся от 0 до sizeof(int) * 8, сдвигая маску на 1 влево каждый раз. Изначально она равна 1 (то есть 00000000 00000000 00000000 00000001), затем 2 (00000000 00000000 00000000 00000010), затем 00000000 00000000 00000000 00000100 и т.д. И если делать `&` маски и числа, мы получим значение бита числа на i-й позиции --- если 0, то там был 0, если не 0, то там была единица.

2021-10-09 15:10 UTC, yurii-litvinov commented on Homework 4/Binary representation/Binary representation/Binary representation.c
> +    return result;
"Упаковка" числа обратно тоже ничего может не знать про знак. Это можно делать тоже маской и битовыми операциями (тут наоборот `|`, поскольку мы хотим "вклеить" бит в уже существующее число), или как Вы, умножением и сложением (что по сути одно и то же --- Вы прибавляете к числу степени двойки, то есть число вида 000..0010..0, при этом в i-м бите числа заведомо 0 --- это как раз `|`). В арифметическом способе о знаке позаботится арифметическое переполнение (потому что на самом деле мы ничего не прибавляем, а просто выписываем в число биты из массива, и если оно было отрицательным, то и станет отрицательным).

2021-10-09 15:10 UTC, yurii-litvinov commented on Homework 4/Binary representation/Binary representation/Binary representation.c
> +        return -1;
additionalArrayForSummand так утечёт

2021-10-09 15:10 UTC, yurii-litvinov commented on Homework 4/Binary representation/Binary representation/Binary representation.c
> +void makeAnAdditionalCode(int startNumber, int additionalArray[], int lengthOfArray)
Он, кстати, по-английски Two's Complement, не additional

2021-10-09 15:10 UTC, yurii-litvinov commented on Homework 4/Binary representation/Binary representation/Binary representation.c
> +        return -1;
А так вообще всё утечёт

2021-10-09 15:10 UTC, yurii-litvinov commented on Homework 4/Binary representation/Binary representation/Binary representation.c
> +    if (!standartTestWithNegativeSummand() || !standartTestWithPositiveSummand() || !testWithNegativeNumbers() || !testWithNegativeNumbers || !testWithNull())
С testWithNegativeNumbers что-то не так :)

2021-10-09 15:10 UTC, yurii-litvinov commented on Homework 4/Binary representation/Binary representation/Binary representation.c
> +    int lengthOfAdditionalArrayForSummand = findLengthOfBinaryRepresentation(summand) + 2;
Для любого int-ового числа длина его двоичного представления --- ровно sizeof(int) * 8, и, кстати, известна во время компиляции, так что можно массивы на куче не выделять

2021-10-09 15:10 UTC, yurii-litvinov commented on Homework 4/Binary representation/Binary representation/Binary representation.c
> +        return -1;
Утечки памяти повсюду :)

2021-10-12 21:16 UTC, YuriUfimtsev commented
Здравствуйте, исправил

2021-10-14 16:00 UTC, yurii-litvinov commented on Homework 4/Binary representation/Binary representation/Binary representation.c
> +    }
И тоже непонятно, зачем

2021-10-18 10:02 UTC, YuriUfimtsev commented
Поправил. Присваивание summand большего слагаемого, а addend меньшего было нужно, когда динамически массивы выделял, чтобы определить, каков максимальный размер массива будет. Но сейчас массивы уже статистически задаю, поэтому да, этот if не нужен, убрал

2021-12-05 12:26 UTC, merged