Задача "Модули и файлы"
YuriUfimtsev/Space-for-homeworks pull request #12
Opened 2021-10-09 13:10 UTC by YuriUfimtsev

2021-10-09 16:54 UTC, yurii-litvinov requested changes
Что-то всё в одном коммите. Я начну подозревать, что Вы гитом пользуетесь как системой для сдачи домашек, а не как инструментом разработки :)

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Modules and files.c
> +#include <stdio.h>
Пробелы в названии весьма не рекомендую. Лучше тоже camelCase использовать

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Modules and files.rc
> +// Microsoft Visual C++ generated resource script.
Это не нужно. Вряд ли этой программе потребуется локализация.

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Modules and files.vcxproj.filters
> +      <Filter>Source Files</Filter>
Nope. Header Files

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Modules and files.vcxproj.filters
> +    <ClCompile Include="sorting.c">
Что-то часть файлов с заглавной, часть со строчной. Может, Вы думаете, что это не важно, но самые популярные файловые системы под Linux (ext4, ReiserFS) так не думают, и с удовольствием сделают так, чтобы Ваша программа не скомпилировалась, стоит чуть-чуть ошибиться в регистре букв файла.

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Sorting.h
> +//��������� ��������� ����� �������.
Надо пробел после `//`

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/resource.h
> +//{{NO_DEPENDENCIES}}
Это тоже не надо на самом деле

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Sorting.h
> +void qSort(int array[], int stopIndex, int startIndex);
Оу, сначала конечный индекс, затем начальный? Это неожиданно, поэтому плохо :)

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/sorting.c
> +    }
Тут тоже, надо вынести в отдельную функцию и применить тернарный оператор

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Modules and files.c
> +        fscanf(file, "%d", &buffer);
Если просто посчитать количество записей, переменная не нужна:
```suggestion
        fscanf(file, "%*d");
```
`*` перед форматным спецификатором означает "считать и выкинуть". Очень удобно, пользуйтесь.

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Modules and files.c
> +    }
И я бы опять-таки этот кусок кода в отдельную функцию вынес. Функции бесплатны, и делают сложные задачи набором простых, что всегда хорошо.

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Modules and files.c
> +    fseek(file, 0, SEEK_SET);
Он и так на нуле, файл только что открыт на чтение

2021-10-09 16:54 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Modules and files.c
> +        return -1;
И файл остался не закрыт

2021-10-18 09:08 UTC, YuriUfimtsev commented
Насчет пробелов в названии, учета регистра в названии файлов и загрузки лишних файлов понял - на будущее учту.

2021-10-20 15:15 UTC, yurii-litvinov requested changes
Почти правильно

2021-10-20 15:15 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/Sorting.h
> +void qSort(int array[], int stopIndex, int startIndex);
В реализации поправили, а тут нет, теперь запутывает ещё больше

2021-10-20 15:15 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/sorting.c
> +    return supportElement;
```suggestion
    return array[i] > array[i - 1] ? array[i] : array[i - 1];
```

2021-10-20 15:15 UTC, yurii-litvinov commented on Homework 4/Modules and files/Modules and files/sorting.c
> +    return true;
Так писать нельзя, это просто пять строк из одной :)

2021-12-05 12:26 UTC, merged