GraphViz
YuriUfimtsev/Space-for-homeworks pull request #46
Opened 2021-12-21 16:44 UTC by YuriUfimtsev

2021-12-21 20:10 UTC, YuriUfimtsev commented
Инструкция:
dot.exe должен лежать по адресу C:\Program Files\Graphviz\bin\dot.exe

2021-12-23 17:04 UTC, yurii-litvinov requested changes
Инструкция должна быть не в комментарии к пуллреквесту, а рядом с проектным файлом в формате .md. Иначе её никто никогда не найдёт. А так почти всё ок, да.

2021-12-23 17:04 UTC, yurii-litvinov commented on Homework11/GraphViz/GraphViz.c
> +            return NULL;
А так утечёт всё, выделенное ранее

2021-12-23 17:04 UTC, yurii-litvinov commented on Homework11/GraphViz/GraphViz.c
> +        fclose(fileWithAdjacencyMatrix);
fclose(fileWithAdjacencyMatrix); можно было до if поднять

2021-12-23 17:52 UTC, yurii-litvinov approved these changes
👍

2021-12-23 19:16 UTC, merged